// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg47FqAzNpHPG-TpnwKbmU8YvYrTfT8vA',
    appId: '1:523045451447:web:4e925d6f1a2459b4ee7f32',
    messagingSenderId: '523045451447',
    projectId: 'capital-19d3a',
    authDomain: 'capital-19d3a.firebaseapp.com',
    storageBucket: 'capital-19d3a.appspot.com',
    measurementId: 'G-54PK51DC71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2ko2wSCDDBKYmSL2AQjAnFZg-8eGe6E',
    appId: '1:523045451447:android:b9649510967aa00aee7f32',
    messagingSenderId: '523045451447',
    projectId: 'capital-19d3a',
    storageBucket: 'capital-19d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrVh4tlQ_2bsqFKT-wTSz_Ja6rhul0aCg',
    appId: '1:523045451447:ios:b79be6548321c4f0ee7f32',
    messagingSenderId: '523045451447',
    projectId: 'capital-19d3a',
    storageBucket: 'capital-19d3a.appspot.com',
    iosClientId: '523045451447-nq66ka5l530f95ta99qmcedcvtato69h.apps.googleusercontent.com',
    iosBundleId: 'com.example.capital',
  );
}
